config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
     sessions: 'users/sessions',
     confirmations: 'users/confirmations',
     passwords: 'users/passwords',
     registrations: 'users/registrations',
     unlocks: 'users/unlocks'
     
   }
  resources :books

   
 

  root 'books#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
	validates :title, presence: true
	validates_uniqueness_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_out_path_for(resource_or_scope)
    books_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_id, only: [:show, :edit, :destroy, :update]
	
	def index
		@books=Book.all
	end

	def new
		@book=Book.new
	end

	def create
		@book=Book.new(book_params)
		if(@book.save)
			redirect_to @book
		else
			render "new"
		end
	end

	def show
	end

	def edit
	end

	def update
		if (@book.update(book_params))
			redirect_to @book
		else
			render "edit" 
		end
	end

	def destroy
		@book.destroy
		redirect_to books_path
	end

	private
	def find_id
		@book=Book.find(params[:id])
	end

	def book_params
		params.require(:book).permit(:title, :author)
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div align="center" background="#HHH">
	<%=form_for @book do |f|%>
	  <p>
		<%=f.label :title%>
		<%=f.text_field :title%>
	  </p>
	  <p>
	    <%=f.label :author%>
	    <%=f.text_field :author%>
	  </p>
	  <p> 
	  	<%=f.submit%>
	  </p>
	<%end%>
</div>

app/views/books/edit.html.erb
<h1><center>Edit <%=@book.title%></center></h1>
<%=render 'form'%>

app/views/books/index.html.erb
<div align="center"><h1>Welcome To The Online Book Library</h1></div>

<%@books.each do |b|%>
 <h3><%=link_to b.title, book_path(b)%></h3>
 <p><strong><%=b.author%></strong></p>
 <%if admin_signed_in?%>
  <p>
   <%=link_to "Edit", edit_book_path(b)%> &nbsp;&nbsp;&nbsp;
   <%=link_to "Delete", book_path(b), method: :delete, data: {confirm: "Are You Sure?"}%>
  </p>
 <%end%>
 <hr>
<%end%>

app/views/books/new.html.erb
<h1><center>Add New Book To Library</center></h1>
<%if admin_signed_in?%>
	<%=render 'form'%>
<%else%>
	Only Admin Can Add A Book
<%end%>

app/views/books/show.html.erb
<%if admin_signed_in?%>
<div class="notice" style="color:green">
You have successfully added a book
</div>
<%end%>
<%if user_signed_in? || admin_signed_in?%>
 <div class="jumbotron" align="center">
<h1>Title:<%=link_to @book.title, "/"+@book.title+".pdf"%></h1>
<p>Author:<%=@book.author%></p>
</div>
<%else%>
<div class="jumbotron" align="center">
<h1>Title:<%=@book.title%></h1>
<p>Author:<%=@book.author%></p>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookLibrary</title>
  <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=render "shared/navbar"%>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
 <div class="container-fluid">
  <div class="navbar-header">
   <button type="button" class="navbar-toggle collapsed" data-toggle=" collapse" data-target="#mycollapse" aria-expanded=false>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
   </button>
   <a class="navbar-brand" href="#">Brand</a>
  </div>
  <div class="collapse navbar-collapse" id="mycollapse">
   <ul class="nav navbar-nav">
    <%if user_signed_in?%>
     <li>
      <%=link_to "Log_Out", destroy_user_session_path(current_user), method: :delete%>
     </li>
    <%elsif admin_signed_in?%>
     <li>
     <%=link_to "New Book", new_book_path%>
     </li>
     <li>
     <%=link_to "Log_Out", destroy_admin_session_path(current_admin), method: :delete%>
     </li>
    <%else%>
     <li>
      <%=link_to "Admin_Log_In", new_admin_session_path%>
     </li>
     <li>
      <%=link_to "User-Log-In", new_user_session_path%>
     </li>
     <li>
      <%=link_to "Sign_Up", new_user_registration_path%>
     </li>
    <%end%>

   </ul>
  </div>
 </div>
</nav>